version: "3"
services:

  # Containers for local development

  localstack_dev:
    container_name: localstack_dev
    depends_on:
      - http_server
      - message_processor
      - localstack_external_deps
    build:
      context: .
    env_file: $PWD/local-stack/.env
    volumes:
      - .:/app
    command:
      - php
      - bin/http-server.php

  http_server:
    container_name: http_server
    build:
      context: .
    env_file: $PWD/local-stack/.env
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./bin:/app/bin
      - ./src:/app/src
    command:
      - php
      - bin/http-server.php

  message_processor:
    container_name: message_processor
    build:
      context: .
    env_file: $PWD/local-stack/.env
    volumes:
      - ./bin:/app/bin
      - ./src:/app/src
    command:
      - php
      - bin/message-processor.php

  # Containers for local development external deps

  localstack_external_deps:
      image: tianon/true
      restart: "no"
      depends_on:
          - postgres
          - pgadmin
          - rabbitmq
          - redis
          - metrics_pushgateway

  postgres:
    container_name: postgres
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    env_file:
      - ./local-stack/.env
    volumes:
      - ./local-stack/postgres/data:/var/lib/postgresql/data/ # persist data even if container shuts down

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.15
    env_file:
      - ./local-stack/.env
    depends_on:
      - 'postgres'
    ports:
      - 5050:5050
    volumes:
      - './local-stack/pgadmin/config/servers.json:/pgadmin4/servers.json'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - ./local-stack/.env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./local-stack/rabbitmq/data:/var/lib/rabbitmq
      - ./local-stack/rabbitmq/logs:/var/log/rabbitmq
      - ./local-stack/rabbitmq/etc:/etc/rabbitmq

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./local-stack/redis/data:/var/lib/redis
    #   - ./local-stack/redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - ./local-stack/.env

  metrics_pushgateway:
    image: prom/pushgateway:latest
    container_name: metrics_pushgateway
    ports:
      - 9091:9091
